# Pure-nix build layer for store-imported (impure-fetched) inputs.
#
# The migration shape: a thin imperative layer fetches the genuinely-networked bits
# (npm cache, pyodide, …), `scripts/store-import.sh` adds each to the store + pins a
# GC root, and `xtask gen-stores` emits ./stores.nix mapping names -> storePath. The
# derivations below then consume those store paths and build OFFLINE in the sandbox,
# so nix owns the graph + caching + invalidation for everything past the fetch.
#
# Evaluate with --impure (builtins.storePath, builtins.currentSystem, and getFlake on
# the dirty tree all require it):
#   nix-build --impure nix/builds.nix -A <attr>
# We reuse the flake's pinned nixpkgs so these match the rest of the build.
let
  flake = builtins.getFlake (toString ../.);
  pkgs = flake.inputs.nixpkgs.legacyPackages.${builtins.currentSystem};
  lib = pkgs.lib;
  # generated by `xtask gen-stores`; {} until the first import is recorded.
  stores = if builtins.pathExists ./stores.nix then import ./stores.nix else { };
  owSrc = stores.ow-src or (throw "ow-src not imported — run scripts/fetch-ow-frontend.sh");

  # Open-WebUI frontend, built OFFLINE from store-imported inputs (the networked
  # `npm ci` + `pyodide:fetch` happen outside, in ninja; their results are imported).
  # We run `vite build` directly — NOT `npm run build`, which would re-run the
  # networked pyodide:fetch.
  ow-frontend = pkgs.stdenv.mkDerivation {
    name = "ow-frontend";
    nativeBuildInputs = [ pkgs.nodejs_22 ];
    dontUnpack = true;
    buildPhase = ''
      runHook preBuild
      export HOME="$TMPDIR"
      # Copy (not symlink) node_modules: vite's config loader resolves symlinks via
      # esbuild, which would chase a symlinked node_modules to its real store-path
      # name and then fail to find sibling packages (kleur, rollup, …). A real
      # ./node_modules dir resolves correctly for every tool. `cp -r` keeps exec bits
      # (esbuild's binary needs them — --no-preserve=mode would strip them -> EACCES);
      # chmod -R u+w then makes the store's read-only copies writable.
      cp -r ${owSrc} src
      chmod -R u+w src && cd src
      cp -r ${stores.ow-node-modules} node_modules && chmod -R u+w node_modules
      mkdir -p static && cp -r ${stores.ow-pyodide} static/pyodide && chmod -R u+w static/pyodide
      # invoke node directly: the .bin shims use `#!/usr/bin/env node`, absent in the sandbox
      node node_modules/vite/bin/vite.js build
      runHook postBuild
    '';
    installPhase = "cp -r build $out";
  };

  # python env carrying the wheel build backend so `python -m build --no-isolation`
  # needs no network (uv/hatchling would otherwise fetch the backend from PyPI).
  buildPython = pkgs.python312.withPackages (ps: [ ps.hatchling ps.build ]);

  # The platform-agnostic open_webui wheel, built OFFLINE. hatchling force-includes
  # build/ -> open_webui/frontend; we supply build/ from the nix ow-frontend instead
  # of letting the custom hatch hook run `npm install && npm run build` (network).
  wheel = pkgs.stdenv.mkDerivation {
    name = "open-webui-wheel";
    nativeBuildInputs = [ buildPython ];
    dontUnpack = true;
    buildPhase = ''
      runHook preBuild
      export HOME="$TMPDIR"
      cp -r ${owSrc} src
      chmod -R u+w src && cd src
      # the pre-built frontend where force-include expects it (build -> open_webui/frontend)
      cp -r ${ow-frontend} build && chmod -R u+w build
      # Strip the custom hatch hook table: hatch_build.py runs `npm install --force &&
      # npm run build` (network) to PRODUCE build/, which we already supply. Dropping
      # the table makes hatchling just force-include our build/.
      awk '/^\[tool\.hatch\.build\.hooks\.custom\]/{skip=1;next} /^\[/{skip=0} !skip{print}' \
        pyproject.toml > pyproject.toml.tmp && mv pyproject.toml.tmp pyproject.toml
      python -m build --wheel --no-isolation --outdir out-wheel
      runHook postBuild
    '';
    installPhase = ''
      mkdir -p $out
      cp out-wheel/*.whl $out/
    '';
  };
in
{
  inherit ow-frontend wheel;

  # Slice 1 proof: a pure derivation consuming every imported store path, showing the
  # fetch -> store-add -> gcroot -> storePath chain feeds offline nix builds. Each
  # ${p} both interpolates the path AND registers it as a real build input (a bare
  # string would NOT be mounted into the sandbox).
  stores-proof = pkgs.runCommand "stores-proof" { } ''
    mkdir -p $out
    echo "imported store paths consumed by nix:" > $out/report.txt
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (n: p: ''
      test -e ${p} || { echo "MISSING import ${n}"; exit 1; }
      echo "  ${n} -> ${p} ($(du -sh ${p} | cut -f1))" >> $out/report.txt
    '') stores)}
    cat $out/report.txt
  '';
}
# expose each import directly too (handy for `nix-build --impure nix/builds.nix -A <name>`)
// stores
