# Pure-nix build layer for store-imported (impure-fetched) inputs.
#
# The migration shape: a thin imperative layer fetches the genuinely-networked bits
# (npm cache, pyodide, …), `scripts/store-import.sh` adds each to the store + pins a
# GC root, and `xtask gen-stores` emits ./stores.nix mapping names -> storePath. The
# derivations below then consume those store paths and build OFFLINE in the sandbox,
# so nix owns the graph + caching + invalidation for everything past the fetch.
#
# Evaluate with --impure (builtins.storePath, builtins.currentSystem, and getFlake on
# the dirty tree all require it):
#   nix-build --impure nix/builds.nix -A <attr>
# We reuse the flake's pinned nixpkgs so these match the rest of the build.
let
  flake = builtins.getFlake (toString ../.);
  pkgs = flake.inputs.nixpkgs.legacyPackages.${builtins.currentSystem};
  lib = pkgs.lib;
  # generated by `xtask gen-stores`; {} until the first import is recorded.
  stores = if builtins.pathExists ./stores.nix then import ./stores.nix else { };
in
{
  # Slice 1 proof: a pure derivation consuming every imported store path, showing the
  # fetch -> store-add -> gcroot -> storePath chain feeds offline nix builds. Each
  # ${p} both interpolates the path AND registers it as a real build input (a bare
  # string would NOT be mounted into the sandbox).
  stores-proof = pkgs.runCommand "stores-proof" { } ''
    mkdir -p $out
    echo "imported store paths consumed by nix:" > $out/report.txt
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (n: p: ''
      test -e ${p} || { echo "MISSING import ${n}"; exit 1; }
      echo "  ${n} -> ${p} ($(du -sh ${p} | cut -f1))" >> $out/report.txt
    '') stores)}
    cat $out/report.txt
  '';
}
# expose each import directly too (handy for `nix-build --impure nix/builds.nix -A <name>`)
// stores
