# plan-ai-usb — pipeline entrypoints. GENERATED by `xtask gen-makefile` from loader.toml — do not edit by hand.
# Run inside `nix develop` (the build leg). TARGET defaults to the host.
TARGET ?=
ifneq ($(TARGET),)
export PLANAI_PLATFORMS ?= $(TARGET)
endif

# Subset the build to specific platforms instead of the lock's full set, e.g.
#   make image PLATFORMS=linux-x64
PLATFORMS ?= $(TARGET)
export PLANAI_PLATFORMS = $(PLATFORMS)

# --- nix develop guard ------------------------------------------------------
GUARDED := $(filter-out clean help,$(or $(MAKECMDGOALS),all))
ifneq ($(GUARDED),)
ifndef PLANAI_DEVSHELL
$(error not in the devshell — run 'nix develop' first, or 'nix develop --command make $(MAKECMDGOALS)')
endif
endif

# Artifact builds go through ninja via the xtask orchestrator (built offline by nix).
XTASK := nix run .\#xtask --

.PHONY: all ninja makefile runtimes components bundles update-tarball tarball-upload download wheel app spa runtime bundle image models dev dev-spa dev-electron dev-usbd dev-usbd-spa vendor-lock update update-deps test test-nixos test-usb test-vm test-all ui seed ollama openwebui download-curl test-clean test-mac test-win docker-image docker-push clean help

all: ## build EVERY target (mac/win/linux/nixos) + image (via ninja)
	$(XTASK) build all

ninja: ## (re)generate build.ninja from the artifact graph
	$(XTASK) gen-ninja

makefile: ## (re)generate this Makefile from loader.toml
	$(XTASK) gen-makefile

runtimes: ## build the python runtime for every target
	$(XTASK) build runtimes

components: ## pack modular component archives (runtimes + all ollama flavours + assets)
	$(XTASK) build components

bundles: ## package every target from the components
	$(XTASK) build bundles

update-tarball: ## update-server tarball (manifest.json + files/) for the update URL
	$(XTASK) build update-tarball

tarball-upload: update-tarball ## upload the update tarball to a web-agency webspace (set WEB_AGENCY_TOKEN + WEB_AGENCY_URL [+ WEB_AGENCY_WEBSPACE_ID])
	$(XTASK) upload

download: ## materialise vendored downloads from Nix FODs (cached) into vendor/
	$(XTASK) build download

wheel: ## build open-webui frontend+wheel + prefetch offline assets
	$(XTASK) build wheel

app: ## install the thin Electron shell deps
	$(XTASK) build app

spa: ## build the Dioxus SPA dashboard into launcher/spa/ (nix build .#spa)
	$(XTASK) build spa

runtime: ## relocatable python runtime for TARGET
	$(XTASK) build runtime-$(TARGET)

bundle: ## package single-file artifact for TARGET
	$(XTASK) build bundle-$(TARGET)

image: ## ready-to-burn FAT32 USB image (all artifacts < 4 GiB; reads everywhere)
	$(XTASK) build image

models: ## pre-pull usb.lock models into ./models (cached; also auto-run by `make image`)
	$(XTASK) build models

dev: ## minimal NixOS build + run (development mode)
	./scripts/dev.sh

dev-spa: ## launch the bundle with a locally built SPA (scripts/build-spa.sh)
	./scripts/build-spa.sh
	dist/bundle/plan-ai.linux-x64.exe --start-with-spa launcher/spa

dev-electron: ## launch the bundle with the local app/ tree (needs: cd app && npm i)
	dist/bundle/plan-ai.linux-x64.exe --start-with-electron app

dev-usbd: ## launch the bundle with a locally built usbd (cargo build --release)
	cd usbd && cargo build --release
	dist/bundle/plan-ai.linux-x64.exe --start-with-usbd usbd/target/release/usbd

dev-usbd-spa: ## launch the prod bundle with BOTH a locally built usbd and SPA
	./scripts/build-spa.sh
	cd usbd && cargo build --release
	dist/bundle/plan-ai.linux-x64.exe --start-with-spa launcher/spa --start-with-usbd usbd/target/release/usbd

vendor-lock: ## regenerate vendor.lock.json (run when usb.lock bumps)
	./scripts/gen-vendor-lock.sh

update: ## regenerate ALL locks after bumping usb.lock (vendor + uv + npm)
	./scripts/update-locks.sh

update-deps: ## bump ollama/open-webui/llmfit/pbs/python to latest + regen locks
	./scripts/update-deps.sh

test: ## lint + runtime import + live ollama/open-webui health
	./scripts/test-build.sh

test-nixos: ## launch the built nixos bundle under xvfb + screenshot
	./scripts/test-nixos.sh

test-usb: ## FAT32 loop-image launch test (models/data on FAT32)
	./scripts/test-usb-image.sh

test-vm: ## run the AppImage in an Ubuntu 26.04 incus VM
	./scripts/test-ubuntu-vm.sh

test-all: ## every test (build/health, nixos, FAT32, ubuntu VM; +mac/win if MAC_TARGET/WIN_TARGET set)
	./scripts/test-build.sh
	./scripts/test-nixos.sh
	./scripts/test-usb-image.sh
	./scripts/test-ubuntu-vm.sh
	@if [ -n "$(MAC_TARGET)" ]; then ./scripts/test-mac.sh; else echo "== skip test-mac (MAC_TARGET unset) =="; fi
	@if [ -n "$(WIN_TARGET)" ]; then ./scripts/test-win.sh; else echo "== skip test-win (WIN_TARGET unset) =="; fi

ui: ## preview the SPA against the mock backend (dx serve + mock API on :9999)
	@echo "==> tailwind + mock API (:9999) + dx serve (hot reload)"
	( cd launcher/spa-src && tailwindcss -i ../../third_party/plan-ai-design/assets/input.css \
	    -o assets/tailwind.css --config tailwind.config.js ) ; \
	  cargo run --manifest-path mock-server/Cargo.toml & \
	  trap 'kill %1 2>/dev/null' EXIT INT TERM ; \
	  ( cd launcher/spa-src && dx serve | cat )

seed: models ## alias of models (pre-pull usb.lock models into ./models)

ollama:
	./scripts/download-ollama.sh

openwebui:
	./scripts/download-openwebui.sh

download-curl: ollama openwebui ## legacy curl-based fetch (no Nix); `make download` (FODs) is preferred

test-clean: ## wipe build outputs and rebuild from scratch (TARGET=linux-x64)
	./scripts/test-clean-build.sh $(TARGET)

test-mac: ## run the mac launcher on a remote mac (set MAC_TARGET=<ssh host>)
	./scripts/test-mac.sh

test-win: ## run the win launcher on a remote windows box (set WIN_TARGET=<ssh host>)
	./scripts/test-win.sh

docker-image: ## build the devshell as a Docker image (result = a loadable archive)
	nix build .#devshell-image
	@echo "==> loadable image at ./result — 'docker load < result' or 'make docker-push IMAGE_REPO=...'"

docker-push: ## push the devshell image to $(IMAGE_REPO) via skopeo (no docker daemon)
	@test -n "$(IMAGE_REPO)" || { echo 'set IMAGE_REPO=<registry/repo:tag>'; exit 1; }
	img=$$(nix build .#devshell-image --no-link --print-out-paths); \
	  skopeo --insecure-policy copy docker-archive:$$img docker://$(IMAGE_REPO)

clean: ## remove all build outputs (ninja graph + dist + every crate's target/)
	@if [ -f build.ninja ] && command -v ninja >/dev/null 2>&1; then echo "ninja -t clean"; ninja -f build.ninja -t clean >/dev/null 2>&1 || true; fi
	rm -rf dist build.ninja .ninja_log .ninja_lock app/node_modules app/.stage app/.stage.lock launcher/target launcher/spa-src/target launcher/spa-src/.cargo mock-server/target crates/*/target third_party/loader/crates/*/target

help: ## list targets
	@grep -hE '^[a-z-]+:.*?## ' $(MAKEFILE_LIST) | sort | \
	  awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'
