#!/usr/bin/env bash
# The IMPURE / networked half of the Open-WebUI frontend build. ninja runs this; nix
# then builds the frontend OFFLINE from the imported result (nix/builds.nix
# `ow-frontend`). Only the genuinely-networked steps live here — `npm ci` (registry)
# and `pyodide:fetch` (jsdelivr + PyPI) — whose outputs are imported into the store
# via store-import.sh so the pure `vite build` can consume them with no network.
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
need node; need npm; need nix; need tar

TAG="$(ow_version)"
SRC="$VENDOR_DIR/open-webui/$TAG/src"
[ -d "$SRC" ] || die "open-webui source missing — run scripts/download-openwebui.sh first"

log "open-webui frontend: npm ci"
( cd "$SRC" && npm ci )
log "open-webui frontend: pyodide:fetch (offline kiosk pyodide + wheels)"
( cd "$SRC" && npm run pyodide:fetch )

# Cleaned source = code only; node_modules + static/pyodide are imported separately
# (build/ + .svelte-kit/ are regenerated by the nix vite build). tar --exclude keeps
# it dependency-free (no rsync in the devshell).
CLEAN="$DIST_DIR/.ow-src"; rm -rf "$CLEAN"; mkdir -p "$CLEAN"
( cd "$SRC" && tar -cf - \
    --exclude=./node_modules --exclude=./build --exclude=./.svelte-kit \
    --exclude=./static/pyodide . ) | tar -xf - -C "$CLEAN"

"$SCRIPT_DIR/store-import.sh" ow-src           "$CLEAN"
"$SCRIPT_DIR/store-import.sh" ow-node-modules  "$SRC/node_modules"
"$SCRIPT_DIR/store-import.sh" ow-pyodide       "$SRC/static/pyodide"
log "ow-frontend inputs imported (ow-src + ow-node-modules + ow-pyodide)"
