//! plan.ai USB build orchestrator. The Makefile is the user entrypoint; it shells
//! to this tool (built offline by nix: `nix run .#xtask`). xtask owns the logic
//! that's painful/unsafe in bash — update-manifest generation (shared with the
//! launcher updater via plan-ai-manifest) and the update-server tarball — and (next)
//! emits a ninja graph for the whole artifact build.

use std::path::PathBuf;
use std::process::Command;

use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "xtask", about = "plan.ai USB build orchestrator")]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Generate an update manifest (JSON) for a drive-layout root directory.
    GenManifest(ManifestArgs),
    /// Assemble the update-server tarball: manifest.json + files/<path>.
    Tarball(TarballArgs),
    /// (Re)write build.ninja describing the whole artifact graph.
    GenNinja,
    /// (Re)write build.ninja then run ninja for the given targets (default: image).
    Build { targets: Vec<String> },
    /// Upload an already-built update tarball to a web-agency webspace.
    Upload(UploadArgs),
}

#[derive(clap::Args)]
struct UploadArgs {
    /// The update tarball to deploy (built by `make update-tarball`).
    #[arg(default_value = "dist/plan-ai-update.tar.gz")]
    tarball: PathBuf,
    /// Deploy token (web-agency).
    #[arg(long, env = "WEB_AGENCY_TOKEN")]
    token: String,
    /// Web-agency server URL.
    #[arg(long, env = "WEB_AGENCY_URL")]
    url: String,
    /// Webspace ID; if omitted, uses the token's scoped webspace.
    #[arg(long, env = "WEB_AGENCY_WEBSPACE_ID")]
    webspace_id: Option<String>,
    /// Cloudflare Pages branch (ignored for local static folders).
    #[arg(long, env = "WEB_AGENCY_BRANCH")]
    branch: Option<String>,
    /// Poll interval (seconds) while waiting for the deployment.
    #[arg(long, default_value = "3")]
    poll_interval: u64,
    /// Don't wait for the deployment to finish.
    #[arg(long)]
    no_wait: bool,
}

#[derive(clap::Args)]
struct ManifestArgs {
    /// Root of the drive layout to scan (e.g. dist/bundle).
    root: PathBuf,
    #[arg(long, default_value = "0.0.0")]
    version: String,
    #[arg(long, default_value = "")]
    commit: String,
    #[arg(long, default_value = plan_ai_manifest::DEFAULT_UPDATE_URL)]
    url: String,
    /// RFC3339 build timestamp (the Makefile passes `date -u`); empty if omitted.
    #[arg(long, default_value = "")]
    built_at: String,
    /// Write here instead of stdout.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(clap::Args)]
struct TarballArgs {
    /// Root of the drive layout to publish (e.g. dist/bundle, all platforms).
    root: PathBuf,
    /// Output tarball path (e.g. dist/plan-ai-update.tar.gz).
    out: PathBuf,
    #[arg(long, default_value = "0.0.0")]
    version: String,
    #[arg(long, default_value = "")]
    commit: String,
    #[arg(long, default_value = plan_ai_manifest::DEFAULT_UPDATE_URL)]
    url: String,
    #[arg(long, default_value = "")]
    built_at: String,
}

fn main() -> Result<()> {
    match Cli::parse().cmd {
        Cmd::GenManifest(a) => gen_manifest(a),
        Cmd::Tarball(a) => tarball(a),
        Cmd::GenNinja => {
            write_ninja()?;
            eprintln!("==> wrote build.ninja");
            Ok(())
        }
        Cmd::Build { targets } => build(targets),
        Cmd::Upload(a) => upload(a),
    }
}

const TARGETS: &[&str] = &["linux-x64", "win-x64", "mac-arm64"];

/// Regenerate build.ninja, then run ninja for `targets` (default: image).
fn build(mut targets: Vec<String>) -> Result<()> {
    write_ninja()?;
    if targets.is_empty() {
        targets.push("image".into());
    }
    run(Command::new("ninja").arg("-f").arg("build.ninja").args(&targets)).context("ninja build")
}

/// Emit a ninja graph for the whole pipeline so EVERY sub-step is dependency-tracked
/// — no stale "just there" outputs feeding a later step. Leaf commands are the
/// existing scripts / nix builds; ninja owns ordering + staleness via stamp files
/// (dist/.ninja/<step>.stamp) plus declared source inputs.
fn write_ninja() -> Result<()> {
    let mut n = String::new();
    n.push_str("# Generated by `xtask gen-ninja` — do not edit by hand.\n");
    n.push_str("# Make is the entrypoint; it calls `nix run .#xtask -- build <target>`.\n\n");
    // stamp = step whose real output is a dir / nix-store path; gen = real file out.
    n.push_str("rule stamp\n  command = mkdir -p dist/.ninja && $cmd && touch $out\n  description = $desc\n\n");
    n.push_str("rule gen\n  command = $cmd\n  description = $desc\n\n");

    let stamp = |s: &str| format!("dist/.ninja/{s}.stamp");
    let mut edges = String::new();
    let mut stamp_edge = |out: &str, deps: &[String], cmd: &str, desc: &str| {
        edges.push_str(&format!("build {}: stamp", stamp(out)));
        for d in deps {
            edges.push(' ');
            edges.push_str(d);
        }
        edges.push_str(&format!("\n  cmd = {cmd}\n  desc = {desc}\n\n"));
    };

    // --- leaf/source-driven steps ------------------------------------------
    stamp_edge("download", &srcs(&["usb.lock", "vendor.lock.json"]), "./scripts/fetch-vendor.sh", "download");
    stamp_edge("wheel", &[stamp("download")], "./scripts/build-openwebui.sh", "openwebui wheel");
    stamp_edge("app", &srcs(&["app/package.json", "app/package-lock.json"]), "cd app && npm ci", "electron deps");
    stamp_edge("spa", &src_tree("launcher/spa-src"), "./scripts/build-spa.sh", "dioxus spa");

    // runtimes per target (need the downloaded interpreter + the wheel)
    let mut runtime_stamps = Vec::new();
    for t in TARGETS {
        let s = stamp(&format!("runtime-{t}"));
        stamp_edge(&format!("runtime-{t}"), &[stamp("download"), stamp("wheel")], &format!("./scripts/make-runtime.sh {t}"), &format!("runtime {t}"));
        runtime_stamps.push(s);
    }

    // components: pack runtimes + ollama flavours + ow-assets
    let mut comp_deps = runtime_stamps.clone();
    comp_deps.push(stamp("wheel"));
    stamp_edge("components", &comp_deps, "./scripts/build-components.sh", "components");

    // bundle per target: depends on components + spa + app + launcher/spinner/crate sources
    let mut bundle_src = src_tree("launcher/src");
    bundle_src.extend(src_tree("spinner/src"));
    bundle_src.extend(src_tree("crates"));
    bundle_src.extend(srcs(&["launcher/Cargo.toml", "launcher/Cargo.lock", "spinner/Cargo.toml", "spinner/Cargo.lock", "scripts/bundle.sh", "flake.nix"]));
    let mut bundle_stamps = Vec::new();
    for t in TARGETS {
        let mut deps = vec![stamp("components"), stamp("spa"), stamp("app")];
        deps.extend(bundle_src.iter().cloned());
        stamp_edge(&format!("bundle-{t}"), &deps, &format!("./scripts/bundle.sh {t}"), &format!("bundle {t}"));
        bundle_stamps.push(stamp(&format!("bundle-{t}")));
    }

    // image + tarball: real-file outputs, depend on every bundle + their scripts
    let mut img_deps = bundle_stamps.clone();
    img_deps.extend(srcs(&["scripts/make-usb-image.sh"]));
    img_deps.extend(src_tree("xtask/src"));
    img_deps.extend(src_tree("crates"));
    edges.push_str(&format!("build dist/plan-ai-usb.img: gen {}\n  cmd = ./scripts/make-usb-image.sh\n  desc = usb image\n\n", img_deps.join(" ")));
    let mut tar_deps = bundle_stamps.clone();
    tar_deps.extend(srcs(&["scripts/make-update-tarball.sh"]));
    tar_deps.extend(src_tree("xtask/src"));
    tar_deps.extend(src_tree("crates"));
    edges.push_str(&format!("build dist/plan-ai-update.tar.gz: gen {}\n  cmd = ./scripts/make-update-tarball.sh\n  desc = update tarball\n\n", tar_deps.join(" ")));

    // phony aliases so `ninja <name>` (and the Makefile) read naturally
    for s in ["download", "wheel", "app", "spa", "components"] {
        edges.push_str(&format!("build {s}: phony {}\n", stamp(s)));
    }
    for t in TARGETS {
        edges.push_str(&format!("build runtime-{t}: phony {}\n", stamp(&format!("runtime-{t}"))));
        edges.push_str(&format!("build bundle-{t}: phony {}\n", stamp(&format!("bundle-{t}"))));
    }
    edges.push_str(&format!("build runtimes: phony {}\n", runtime_stamps.join(" ")));
    edges.push_str(&format!("build bundles: phony {}\n", bundle_stamps.join(" ")));
    edges.push_str("build image: phony dist/plan-ai-usb.img\n");
    edges.push_str("build update-tarball: phony dist/plan-ai-update.tar.gz\n");
    edges.push_str("build all: phony dist/plan-ai-usb.img\n");
    edges.push_str("default image\n");

    n.push_str(&edges);
    std::fs::write("build.ninja", n).context("writing build.ninja")?;
    Ok(())
}

/// Existing files from the list (skip missing — e.g. an optional lock).
fn srcs(paths: &[&str]) -> Vec<String> {
    paths.iter().filter(|p| PathBuf::from(p).exists()).map(|p| p.to_string()).collect()
}

/// All source files under `root` (recursively), skipping build dirs. Used as ninja
/// inputs so editing code re-triggers the dependent steps.
fn src_tree(root: &str) -> Vec<String> {
    let mut out = Vec::new();
    fn walk(dir: &std::path::Path, out: &mut Vec<String>) {
        let Ok(rd) = std::fs::read_dir(dir) else { return };
        for e in rd.flatten() {
            let p = e.path();
            let name = e.file_name();
            let name = name.to_string_lossy();
            if name == "target" || name == ".git" || name == "node_modules" {
                continue;
            }
            if p.is_dir() {
                walk(&p, out);
            } else {
                out.push(p.to_string_lossy().replace('\\', "/"));
            }
        }
    }
    walk(&PathBuf::from(root), &mut out);
    out.sort();
    out
}

fn gen_manifest(a: ManifestArgs) -> Result<()> {
    let m = plan_ai_manifest::generate(&a.root, &a.version, &a.commit, &a.url, &a.built_at)
        .with_context(|| format!("scanning {}", a.root.display()))?;
    let json = m.to_json_pretty();
    match a.out {
        Some(p) => std::fs::write(&p, json).with_context(|| format!("writing {}", p.display()))?,
        None => println!("{json}"),
    }
    Ok(())
}

fn tarball(a: TarballArgs) -> Result<()> {
    // Resolve to an absolute path so the staged `files` symlink is valid wherever
    // tar runs. The root is a curated symlink mirror of the drive (the scripts
    // build it, excluding electron-builder's *-unpacked dirs).
    let root = std::fs::canonicalize(&a.root).with_context(|| format!("canonicalize {}", a.root.display()))?;
    let m = plan_ai_manifest::generate(&root, &a.version, &a.commit, &a.url, &a.built_at)
        .with_context(|| format!("scanning {}", root.display()))?;
    let stage = a.out.with_extension("stage");
    let _ = std::fs::remove_dir_all(&stage);
    std::fs::create_dir_all(&stage)?;
    // files/ -> the mirror; `tar -h` dereferences symlinks so real content lands
    // under files/<path> (no GB copy). manifest.json sits beside it at the root.
    std::os::unix::fs::symlink(&root, stage.join("files"))?;
    std::fs::write(stage.join("manifest.json"), m.to_json_pretty())?;
    if let Some(parent) = a.out.parent() {
        std::fs::create_dir_all(parent)?;
    }
    run(Command::new("tar").arg("-C").arg(&stage).arg("-czhf").arg(&a.out).arg("manifest.json").arg("files"))
        .context("creating tarball")?;
    let _ = std::fs::remove_dir_all(&stage);
    eprintln!("==> update tarball -> {} ({} files)", a.out.display(), m.files.len());
    Ok(())
}

fn run(cmd: &mut Command) -> Result<()> {
    let status = cmd.status().with_context(|| format!("spawning {cmd:?}"))?;
    if !status.success() {
        bail!("command failed ({status}): {cmd:?}");
    }
    Ok(())
}

// ── web-agency upload (HTTP protocol adopted from mac-mgmt's web-agency-upload) ──

#[derive(serde::Deserialize)]
struct Whoami {
    kind: String,
    webspace_id: Option<String>,
    webspace_name: Option<String>,
}
#[derive(serde::Deserialize)]
struct UploadResp {
    deployment_id: String,
    status: String,
}
#[derive(serde::Deserialize)]
struct StatusResp {
    deployment_id: String,
    status: String,
    error_message: Option<String>,
}

fn upload(a: UploadArgs) -> Result<()> {
    let _ = rustls::crypto::ring::default_provider().install_default();
    let client = reqwest::blocking::Client::new();
    deploy(&client, &a)
}

/// whoami (if no webspace) → POST the tarball → poll status. Split out so tests can
/// drive it against a local server.
fn deploy(client: &reqwest::blocking::Client, a: &UploadArgs) -> Result<()> {
    let base = a.url.trim_end_matches('/');
    let webspace = match &a.webspace_id {
        Some(id) => id.clone(),
        None => resolve_webspace(client, base, &a.token)?,
    };
    if !a.tarball.is_file() {
        bail!("{} not found — run `make update-tarball` first", a.tarball.display());
    }
    let mut url = format!("{base}/api/v1/deploy/{webspace}");
    if let Some(b) = &a.branch {
        url.push_str(&format!("?branch={}", percent(b)));
    }
    eprintln!("uploading {} to webspace {webspace}…", a.tarball.display());
    let body = reqwest::blocking::Body::from(std::fs::File::open(&a.tarball)?);
    let resp = client.post(&url).bearer_auth(&a.token).body(body).send().context("upload failed")?;
    if !resp.status().is_success() {
        let s = resp.status();
        bail!("upload failed ({s}): {}", resp.text().unwrap_or_default());
    }
    let up: UploadResp = resp.json().context("invalid upload response")?;
    eprintln!("deployment {} started ({})", up.deployment_id, up.status);
    if a.no_wait {
        println!("{}", serde_json::json!({ "deployment_id": up.deployment_id, "status": up.status }));
        return Ok(());
    }
    loop {
        std::thread::sleep(std::time::Duration::from_secs(a.poll_interval));
        let resp = client.get(format!("{base}/api/v1/deploy/{webspace}/status")).bearer_auth(&a.token).send().context("status check failed")?;
        if !resp.status().is_success() {
            eprintln!("warning: status check failed: {}", resp.text().unwrap_or_default());
            continue;
        }
        let st: StatusResp = resp.json().context("invalid status response")?;
        match st.status.as_str() {
            "success" => {
                eprintln!("deployment {} successful", st.deployment_id);
                return Ok(());
            }
            "failed" => bail!("deployment failed: {}", st.error_message.unwrap_or_else(|| "unknown error".into())),
            other => eprintln!("status: {other}"),
        }
    }
}

fn resolve_webspace(client: &reqwest::blocking::Client, base: &str, token: &str) -> Result<String> {
    let resp = client.get(format!("{base}/api/v1/deploy/whoami")).bearer_auth(token).send().context("failed to reach server")?;
    if !resp.status().is_success() {
        let s = resp.status();
        bail!("whoami failed ({s}): {}", resp.text().unwrap_or_default());
    }
    let w: Whoami = resp.json().context("invalid whoami response")?;
    if w.kind != "deploy" {
        bail!("token kind is '{}', expected 'deploy'", w.kind);
    }
    let name = w.webspace_name.as_deref().unwrap_or("unknown");
    w.webspace_id
        .inspect(|id| eprintln!("using token's scoped webspace: {name} ({id})"))
        .ok_or_else(|| anyhow::anyhow!("token not scoped to a webspace — pass --webspace-id"))
}

/// Percent-encode a path/query segment (branch names).
fn percent(s: &str) -> String {
    s.bytes()
        .map(|b| match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => (b as char).to_string(),
            _ => format!("%{b:02X}"),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{Read, Write};

    /// A one-shot HTTP/1.1 server that replies to each request with a canned body,
    /// consuming any Content-Length body first so the client doesn't block.
    fn serve(responses: Vec<(&'static str, &'static str)>) -> (String, std::thread::JoinHandle<()>) {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        let resp: Vec<(String, String)> = responses.into_iter().map(|(a, b)| (a.into(), b.into())).collect();
        let h = std::thread::spawn(move || {
            for (code, body) in resp {
                let (mut sock, _) = listener.accept().unwrap();
                // Read headers, then drain a Content-Length body if present.
                let mut buf = Vec::new();
                let mut tmp = [0u8; 1024];
                let mut content_len = 0usize;
                loop {
                    let n = sock.read(&mut tmp).unwrap();
                    if n == 0 {
                        break;
                    }
                    buf.extend_from_slice(&tmp[..n]);
                    if let Some(p) = buf.windows(4).position(|w| w == b"\r\n\r\n") {
                        let head = String::from_utf8_lossy(&buf[..p]).to_lowercase();
                        content_len = head
                            .lines()
                            .find_map(|l| l.strip_prefix("content-length:"))
                            .and_then(|v| v.trim().parse::<usize>().ok())
                            .unwrap_or(0);
                        let have = buf.len() - (p + 4);
                        let mut remaining = content_len.saturating_sub(have);
                        while remaining > 0 {
                            let n = sock.read(&mut tmp).unwrap();
                            if n == 0 {
                                break;
                            }
                            remaining = remaining.saturating_sub(n);
                        }
                        break;
                    }
                }
                let out = format!(
                    "HTTP/1.1 {code}\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{body}",
                    body.len()
                );
                sock.write_all(out.as_bytes()).unwrap();
            }
        });
        (format!("http://{addr}"), h)
    }

    fn test_client() -> reqwest::blocking::Client {
        let _ = rustls::crypto::ring::default_provider().install_default();
        reqwest::blocking::Client::new()
    }

    fn args(url: String, tarball: PathBuf) -> UploadArgs {
        UploadArgs {
            tarball,
            token: "t".into(),
            url,
            webspace_id: Some("ws1".into()),
            branch: None,
            poll_interval: 0,
            no_wait: false,
        }
    }

    #[test]
    fn deploy_uploads_then_polls_to_success() {
        let tb = std::env::temp_dir().join(format!("xtask-upl-{}.tar.gz", std::process::id()));
        std::fs::write(&tb, b"fake tarball").unwrap();
        let (url, h) = serve(vec![
            ("200 OK", r#"{"deployment_id":"d1","status":"queued"}"#), // POST upload
            ("200 OK", r#"{"deployment_id":"d1","status":"success"}"#), // GET status
        ]);
        let client = test_client();
        let r = deploy(&client, &args(url, tb.clone()));
        h.join().unwrap();
        std::fs::remove_file(&tb).ok();
        assert!(r.is_ok(), "{r:?}");
    }

    #[test]
    fn deploy_reports_failed_deployment() {
        let tb = std::env::temp_dir().join(format!("xtask-upl2-{}.tar.gz", std::process::id()));
        std::fs::write(&tb, b"fake").unwrap();
        let (url, h) = serve(vec![
            ("200 OK", r#"{"deployment_id":"d2","status":"queued"}"#),
            ("200 OK", r#"{"deployment_id":"d2","status":"failed","error_message":"boom"}"#),
        ]);
        let client = test_client();
        let r = deploy(&client, &args(url, tb.clone()));
        h.join().unwrap();
        std::fs::remove_file(&tb).ok();
        assert!(r.is_err());
        assert!(r.unwrap_err().to_string().contains("boom"));
    }
}
