//! plan.ai USB build orchestrator. The Makefile is the user entrypoint; it shells
//! to this tool (built offline by nix: `nix run .#xtask`). xtask owns the logic
//! that's painful/unsafe in bash — update-manifest generation (shared with the
//! launcher updater via plan-ai-manifest) and the update-server tarball — and (next)
//! emits a ninja graph for the whole artifact build.

use std::path::PathBuf;
use std::process::Command;

use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "xtask", about = "plan.ai USB build orchestrator")]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Generate an update manifest (JSON) for a drive-layout root directory.
    GenManifest(ManifestArgs),
    /// Assemble the update-server tarball: manifest.json + files/<path>.
    Tarball(TarballArgs),
    /// (Re)write build.ninja describing the whole artifact graph.
    GenNinja,
    /// (Re)write build.ninja then run ninja for the given targets (default: image).
    Build { targets: Vec<String> },
}

#[derive(clap::Args)]
struct ManifestArgs {
    /// Root of the drive layout to scan (e.g. dist/bundle).
    root: PathBuf,
    #[arg(long, default_value = "0.0.0")]
    version: String,
    #[arg(long, default_value = "")]
    commit: String,
    #[arg(long, default_value = plan_ai_manifest::DEFAULT_UPDATE_URL)]
    url: String,
    /// RFC3339 build timestamp (the Makefile passes `date -u`); empty if omitted.
    #[arg(long, default_value = "")]
    built_at: String,
    /// Write here instead of stdout.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(clap::Args)]
struct TarballArgs {
    /// Root of the drive layout to publish (e.g. dist/bundle, all platforms).
    root: PathBuf,
    /// Output tarball path (e.g. dist/plan-ai-update.tar.gz).
    out: PathBuf,
    #[arg(long, default_value = "0.0.0")]
    version: String,
    #[arg(long, default_value = "")]
    commit: String,
    #[arg(long, default_value = plan_ai_manifest::DEFAULT_UPDATE_URL)]
    url: String,
    #[arg(long, default_value = "")]
    built_at: String,
}

fn main() -> Result<()> {
    match Cli::parse().cmd {
        Cmd::GenManifest(a) => gen_manifest(a),
        Cmd::Tarball(a) => tarball(a),
        Cmd::GenNinja => {
            write_ninja()?;
            eprintln!("==> wrote build.ninja");
            Ok(())
        }
        Cmd::Build { targets } => build(targets),
    }
}

const TARGETS: &[&str] = &["linux-x64", "win-x64", "mac-arm64"];

/// Regenerate build.ninja, then run ninja for `targets` (default: image).
fn build(mut targets: Vec<String>) -> Result<()> {
    write_ninja()?;
    if targets.is_empty() {
        targets.push("image".into());
    }
    run(Command::new("ninja").arg("-f").arg("build.ninja").args(&targets)).context("ninja build")
}

/// Emit a ninja graph for the whole pipeline so EVERY sub-step is dependency-tracked
/// — no stale "just there" outputs feeding a later step. Leaf commands are the
/// existing scripts / nix builds; ninja owns ordering + staleness via stamp files
/// (dist/.ninja/<step>.stamp) plus declared source inputs.
fn write_ninja() -> Result<()> {
    let mut n = String::new();
    n.push_str("# Generated by `xtask gen-ninja` — do not edit by hand.\n");
    n.push_str("# Make is the entrypoint; it calls `nix run .#xtask -- build <target>`.\n\n");
    // stamp = step whose real output is a dir / nix-store path; gen = real file out.
    n.push_str("rule stamp\n  command = mkdir -p dist/.ninja && $cmd && touch $out\n  description = $desc\n\n");
    n.push_str("rule gen\n  command = $cmd\n  description = $desc\n\n");

    let stamp = |s: &str| format!("dist/.ninja/{s}.stamp");
    let mut edges = String::new();
    let mut stamp_edge = |out: &str, deps: &[String], cmd: &str, desc: &str| {
        edges.push_str(&format!("build {}: stamp", stamp(out)));
        for d in deps {
            edges.push(' ');
            edges.push_str(d);
        }
        edges.push_str(&format!("\n  cmd = {cmd}\n  desc = {desc}\n\n"));
    };

    // --- leaf/source-driven steps ------------------------------------------
    stamp_edge("download", &srcs(&["usb.lock", "vendor.lock.json"]), "./scripts/fetch-vendor.sh", "download");
    stamp_edge("wheel", &[stamp("download")], "./scripts/build-openwebui.sh", "openwebui wheel");
    stamp_edge("app", &srcs(&["app/package.json", "app/package-lock.json"]), "cd app && npm ci", "electron deps");
    stamp_edge("spa", &src_tree("launcher/spa-src"), "./scripts/build-spa.sh", "dioxus spa");

    // runtimes per target (need the downloaded interpreter + the wheel)
    let mut runtime_stamps = Vec::new();
    for t in TARGETS {
        let s = stamp(&format!("runtime-{t}"));
        stamp_edge(&format!("runtime-{t}"), &[stamp("download"), stamp("wheel")], &format!("./scripts/make-runtime.sh {t}"), &format!("runtime {t}"));
        runtime_stamps.push(s);
    }

    // components: pack runtimes + ollama flavours + ow-assets
    let mut comp_deps = runtime_stamps.clone();
    comp_deps.push(stamp("wheel"));
    stamp_edge("components", &comp_deps, "./scripts/build-components.sh", "components");

    // bundle per target: depends on components + spa + app + launcher/spinner/crate sources
    let mut bundle_src = src_tree("launcher/src");
    bundle_src.extend(src_tree("spinner/src"));
    bundle_src.extend(src_tree("crates"));
    bundle_src.extend(srcs(&["launcher/Cargo.toml", "launcher/Cargo.lock", "spinner/Cargo.toml", "spinner/Cargo.lock", "scripts/bundle.sh", "flake.nix"]));
    let mut bundle_stamps = Vec::new();
    for t in TARGETS {
        let mut deps = vec![stamp("components"), stamp("spa"), stamp("app")];
        deps.extend(bundle_src.iter().cloned());
        stamp_edge(&format!("bundle-{t}"), &deps, &format!("./scripts/bundle.sh {t}"), &format!("bundle {t}"));
        bundle_stamps.push(stamp(&format!("bundle-{t}")));
    }

    // image + tarball: real-file outputs, depend on every bundle + their scripts
    let mut img_deps = bundle_stamps.clone();
    img_deps.extend(srcs(&["scripts/make-usb-image.sh"]));
    img_deps.extend(src_tree("xtask/src"));
    img_deps.extend(src_tree("crates"));
    edges.push_str(&format!("build dist/plan-ai-usb.img: gen {}\n  cmd = ./scripts/make-usb-image.sh\n  desc = usb image\n\n", img_deps.join(" ")));
    let mut tar_deps = bundle_stamps.clone();
    tar_deps.extend(srcs(&["scripts/make-update-tarball.sh"]));
    tar_deps.extend(src_tree("xtask/src"));
    tar_deps.extend(src_tree("crates"));
    edges.push_str(&format!("build dist/plan-ai-update.tar.gz: gen {}\n  cmd = ./scripts/make-update-tarball.sh\n  desc = update tarball\n\n", tar_deps.join(" ")));

    // phony aliases so `ninja <name>` (and the Makefile) read naturally
    for s in ["download", "wheel", "app", "spa", "components"] {
        edges.push_str(&format!("build {s}: phony {}\n", stamp(s)));
    }
    for t in TARGETS {
        edges.push_str(&format!("build runtime-{t}: phony {}\n", stamp(&format!("runtime-{t}"))));
        edges.push_str(&format!("build bundle-{t}: phony {}\n", stamp(&format!("bundle-{t}"))));
    }
    edges.push_str(&format!("build runtimes: phony {}\n", runtime_stamps.join(" ")));
    edges.push_str(&format!("build bundles: phony {}\n", bundle_stamps.join(" ")));
    edges.push_str("build image: phony dist/plan-ai-usb.img\n");
    edges.push_str("build update-tarball: phony dist/plan-ai-update.tar.gz\n");
    edges.push_str("build all: phony dist/plan-ai-usb.img\n");
    edges.push_str("default image\n");

    n.push_str(&edges);
    std::fs::write("build.ninja", n).context("writing build.ninja")?;
    Ok(())
}

/// Existing files from the list (skip missing — e.g. an optional lock).
fn srcs(paths: &[&str]) -> Vec<String> {
    paths.iter().filter(|p| PathBuf::from(p).exists()).map(|p| p.to_string()).collect()
}

/// All source files under `root` (recursively), skipping build dirs. Used as ninja
/// inputs so editing code re-triggers the dependent steps.
fn src_tree(root: &str) -> Vec<String> {
    let mut out = Vec::new();
    fn walk(dir: &std::path::Path, out: &mut Vec<String>) {
        let Ok(rd) = std::fs::read_dir(dir) else { return };
        for e in rd.flatten() {
            let p = e.path();
            let name = e.file_name();
            let name = name.to_string_lossy();
            if name == "target" || name == ".git" || name == "node_modules" {
                continue;
            }
            if p.is_dir() {
                walk(&p, out);
            } else {
                out.push(p.to_string_lossy().replace('\\', "/"));
            }
        }
    }
    walk(&PathBuf::from(root), &mut out);
    out.sort();
    out
}

fn gen_manifest(a: ManifestArgs) -> Result<()> {
    let m = plan_ai_manifest::generate(&a.root, &a.version, &a.commit, &a.url, &a.built_at)
        .with_context(|| format!("scanning {}", a.root.display()))?;
    let json = m.to_json_pretty();
    match a.out {
        Some(p) => std::fs::write(&p, json).with_context(|| format!("writing {}", p.display()))?,
        None => println!("{json}"),
    }
    Ok(())
}

fn tarball(a: TarballArgs) -> Result<()> {
    // Resolve to an absolute path so the staged `files` symlink is valid wherever
    // tar runs. The root is a curated symlink mirror of the drive (the scripts
    // build it, excluding electron-builder's *-unpacked dirs).
    let root = std::fs::canonicalize(&a.root).with_context(|| format!("canonicalize {}", a.root.display()))?;
    let m = plan_ai_manifest::generate(&root, &a.version, &a.commit, &a.url, &a.built_at)
        .with_context(|| format!("scanning {}", root.display()))?;
    let stage = a.out.with_extension("stage");
    let _ = std::fs::remove_dir_all(&stage);
    std::fs::create_dir_all(&stage)?;
    // files/ -> the mirror; `tar -h` dereferences symlinks so real content lands
    // under files/<path> (no GB copy). manifest.json sits beside it at the root.
    std::os::unix::fs::symlink(&root, stage.join("files"))?;
    std::fs::write(stage.join("manifest.json"), m.to_json_pretty())?;
    if let Some(parent) = a.out.parent() {
        std::fs::create_dir_all(parent)?;
    }
    run(Command::new("tar").arg("-C").arg(&stage).arg("-czhf").arg(&a.out).arg("manifest.json").arg("files"))
        .context("creating tarball")?;
    let _ = std::fs::remove_dir_all(&stage);
    eprintln!("==> update tarball -> {} ({} files)", a.out.display(), m.files.len());
    Ok(())
}

fn run(cmd: &mut Command) -> Result<()> {
    let status = cmd.status().with_context(|| format!("spawning {cmd:?}"))?;
    if !status.success() {
        bail!("command failed ({status}): {cmd:?}");
    }
    Ok(())
}
